name: Build Angular App

on:
  workflow_call:
    working-directory:
      required: true
      type: string
    base-href:
      required: true
      type: string

  workflow_dispatch: {}

jobs:
  build_angular:
    name: 'Build Angular'
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.1'
        cache: npm
        cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json
    
    - name: Install Angular CLI
      run: npm install -g @angular/cli@19.0.6

    - name: Install Dependencies
      run: npm install
    
    - name: Lint
      if: inputs.run-lint
      run: npx ng lint

    - name: Run Tests
      if: inputs.run-tests
      run: npx ng test --watch=false --browsers=ChromeHeadless

    - name: Build Angular
      run: npx ng build --base-href "${{ inputs.base-href }}"

    # - name: SonarCloud Scan
    #   uses: SonarSource/sonarcloud-github-action@master
    #   with:
    #     projectBaseDir: './website'
    #     organization: 'hiagop22'
    #     projectKey: 'personal-website'
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: angular-build
        path: ${{ inputs.working-directory }}/dist
        retention-days: 1
