name: Build Angular App

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  build_angular:
    name: 'Build Angular'
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    defaults:
      run:
        shell: bash
        working-directory: website
        
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.1'
    
    - name: Install Angular CLI
      run: npm install -g @angular/cli@19.0.6

    - name: Install Website Dependencies
      run: npm install
    
    - name: Build Angular App
      run: ng build --base-href "https://aih.dev.br/"

    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v5.0.0
      with:
        args: >
          -Dsonar.organization=hiagop22
          -Dsonar.projectKey=personal-website
          -Dsonar.sources=./website
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: angular-build
        path: website/dist
        retention-days: 1
