name: CI

on:
  pull_request:
    branches:
      - master

jobs:

  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      infra: ${{ steps.filter.outputs.infra }}
      website: ${{ steps.filter.outputs.website }}

    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            infra:
              - 'infrastructure/**'
            website:
              - 'website/**'

  website_ci:
    needs: detect_changes
    if: needs.detect_changes.outputs.website == 'true'
    uses: ./.github/workflows/website-ci.yaml

  infrastructure_ci:
    needs: detect_changes
    if: needs.detect_changes.outputs.infra == 'true'
    uses: ./.github/workflows/infrastructure-ci.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  final_status:
    runs-on: ubuntu-latest
    needs:
      - website_ci
      - infrastructure_ci
    if: always()

    steps:
      - name: Validate pipeline result
        run: |
          if [[ "${{ needs.website_ci.result }}" == "failure" || \
                "${{ needs.infrastructure_ci.result }}" == "failure" ]]; then
            echo "CI failed"
            exit 1
          fi