name: CI

on:
  pull_request:
    branches:
      - master

jobs:

  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      infra: ${{ steps.filter.outputs.infra }}
      website: ${{ steps.filter.outputs.website }}

    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            infra:
              - 'infrastructure/**'
            website:
              - 'website/**'

  website_ci:
    needs: detect_changes
    if: needs.detect_changes.outputs.website == 'true'
    uses: ./.github/workflows/website-ci.yaml

  infrastructure_ci:
    needs: detect_changes
    if: needs.detect_changes.outputs.infra == 'true'
    uses: ./.github/workflows/infrastructure-ci.yaml